### ISSUE TITLE
Css colours for scroll and builder menu

### ISSUE THREAD

**Issue by tr90814** [tr90814/farewill#12]
The digital/stuff colours need swapping
![image](https://cloud.githubusercontent.com/assets/4854248/7923186/1b8bcb54-08a9-11e5-8b52-fd14a962a958.png)
![image](https://cloud.githubusercontent.com/assets/4854248/7923199/2c0e97e0-08a9-11e5-8bb2-6cc857aa95bf.png)

**Comment by tr90814** [comment]
Maybe do the text colour too? There should be useful classes on a containing element.

**Comment by anttonp** [comment]
Done!
