### ISSUE TITLE
Hook up login

### ISSUE THREAD

**Issue by tr90814** [tr90814/farewill#4]
Remove ui
use Accounts.login etc.

**Comment by tr90814** [comment]
Login states/errors?

**Comment by tr90814** [comment]
http://docs.meteor.com/#/full/meteor_loginwithpassword

**Comment by anttonp** [comment]
Thanks!

**Comment by tr90814** [comment]
http://blog.benmcmahen.com/post/41741539120/building-a-customized-accounts-ui-for-meteor
That might be useful too. If you get stuck i'm happy to have a go.

**Comment by tr90814** [comment]
Done
