### ISSUE TITLE
.DS_Store

### ISSUE THREAD

**Issue by anttonp** [tr90814/farewill#5]
Tom, I'm having problems with the DSstore files.

I cant pull from gitHub. Is because you aren't filtering them? Or is because Dan uploaded something?
![screen shot 2015-06-01 at 10 53 30](https://cloud.githubusercontent.com/assets/11814997/7910455/b9205e5a-084c-11e5-9fc4-eaf0997a7afe.png)

What should I do to pull?

**Comment by tr90814** [comment]
Yeh I need to try again to sort that out.
To pull do a stash first by running `git stash` then try pulling down like normal. You can then run `git stash apply` to get your changes back but you will have merge conflicts.  
Run 
`find . -name .DS_Store -print0 | xargs -0 git rm -f --ignore-unmatch`
Which should remove the .DS_Store files.
Let me know how that goes.

**Comment by tr90814** [comment]
You can check what files have conflicts or are added/not by running `git status`.

**Comment by anttonp** [comment]
Still can’t. 

It gives me the same error.

-- 
Antton Peña
+34 616 701520

On 1 Jun 2015 at 11:09:54, Tom Rogers (notifications@github.com) wrote:

Yeh I need to try again to sort that out.
To pull do a stash first by running git stash then try pulling down like normal. You can then run git stash apply to get your changes back but you will have merge conflicts.

Run
find . -name .DS_Store -print0 | xargs -0 git rm -f --ignore-unmatch
Which should remove the .DS_Store files.
Let me know how that goes.

**Comment by tr90814** [comment]
Try running the `find . -name .DS_Store -print0 | xargs -0 git rm -f --ignore-unmatch` first then.

**Comment by anttonp** [comment]
I did, but no way. 

Is there any way to delete all the files, and clone it again? 


-- 
Antton Peña
+34 616 701520

On 1 Jun 2015 at 11:19:33, Tom Rogers (notifications@github.com) wrote:

Try running the find . -name .DS_Store -print0 | xargs -0 git rm -f --ignore-unmatch first then.

**Comment by tr90814** [comment]
Yeh,  commit any changes you have to a new branch (something like `safety-commit`). Then  `git checkout master` to get back to the master branch and run:
`git fetch --all`
`git reset --hard origin/master`

**Comment by tr90814** [comment]
That should make all your local files match the origin/master exactly

**Comment by anttonp** [comment]
Cool, done! 

I’ll work on the builder then. 

Did u delete the blocks in the scroll? 


-- 
Antton Peña
+34 616 701520

On 1 Jun 2015 at 11:26:25, Tom Rogers (notifications@github.com) wrote:

That should make all your local files match the origin/master exactly

**Comment by tr90814** [comment]
Yeh sort of I started substituting in code to reflect the actual DB state, but haven't finished so nothing will show probs.

**Comment by anttonp** [comment]
Cool, sorry to bother you that much. 

Can you merge the last request I’ve sent. 

It tells me I can’t. 


-- 
Antton Peña
+34 616 701520

On 1 Jun 2015 at 11:32:22, Tom Rogers (notifications@github.com) wrote:

Yeh sort of I started substituting in code to reflect the actual DB state, but haven't finished so nothing will show probs.

**Comment by tr90814** [comment]
No worries, I should have fixed that .DS_store issue properly.

I'll have a look.

**Comment by anttonp** [comment]
Awesome.

Thanks, I’m now able to pull properly, but I don’t have the latest version. The merge request should bring everything up to date. 


-- 
Antton Peña
+34 616 701520

On 1 Jun 2015 at 11:35:42, Tom Rogers (notifications@github.com) wrote:

No worries, I should have fixed that .DS_store issue properly.

I'll have a look.

**Comment by tr90814** [comment]
Problem seems to have gone away
