### ISSUE TITLE
Access to builder

### ISSUE THREAD

**Issue by anttonp** [tr90814/farewill#9]
Tom, 

I got too stuck with the login, so I'll leave it for when you come. 

I'm now trying to access the builder, but I get the login page if I go to: http://localhost:3000/types/stuff/builder.

Thanks!

**Comment by tr90814** [comment]
OK, I've taken off the being logged in requirement until we sort login.  Give it 5mins to build and then try 
`http://localhost:3000/types/stuff/builder/new`

**Comment by tr90814** [comment]
Also if you want to make sure I see any issue quickly feel free to assign me, that way i'll get an email notification.

**Comment by anttonp** [comment]
Awesome! 

Thanks!! 
-- 
Antton Peña
+34 616 701520

On 1 Jun 2015 at 16:44:49, Tom Rogers (notifications@github.com) wrote:

OK, I've taken off the being logged in requirement until we sort login. Give it 5mins to build and then try
http://localhost:3000/types/stuff/builder/new

**Comment by tr90814** [comment]
You'll have to pull down the latest master (ignore the 5mins bit)

**Comment by tr90814** [comment]
This should be fine now
